### ISSUE TITLE
Properties do not align with latest Spring Boot

### ISSUE THREAD

**Issue by ghillert** [pivotal-cf/spring-cloud-sso-connector#7]
It looks like the generated properties do not align properly with Spring Boot any longer. 

For example in regards to property `security.oauth2.client.clientId`:

In the latest Spring Boot version (I believe starting `1.5`) the camel-case version is no longer supported. Instead the proper is now `security.oauth2.client.client-id`.

It would be nice if the properties could somehow align again. A workaround is to do something like:

```yaml
security:
  oauth2:
    client:
      client-id: ${security.oauth2.client.clientId}
```
